// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert'];
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb'];
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem'];
    AButton: typeof import('@arco-design/web-vue')['Button'];
    ACard: typeof import('@arco-design/web-vue')['Card'];
    ACarousel: typeof import('@arco-design/web-vue')['Carousel'];
    ACarouselItem: typeof import('@arco-design/web-vue')['CarouselItem'];
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox'];
    ACol: typeof import('@arco-design/web-vue')['Col'];
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider'];
    ADivider: typeof import('@arco-design/web-vue')['Divider'];
    ADrawer: typeof import('@arco-design/web-vue')['Drawer'];
    AForm: typeof import('@arco-design/web-vue')['Form'];
    AFormItem: typeof import('@arco-design/web-vue')['FormItem'];
    AGrid: typeof import('@arco-design/web-vue')['Grid'];
    AGridItem: typeof import('@arco-design/web-vue')['GridItem'];
    AInput: typeof import('@arco-design/web-vue')['Input'];
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber'];
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword'];
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch'];
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter'];
    ALink: typeof import('@arco-design/web-vue')['Link'];
    AModal: typeof import('@arco-design/web-vue')['Modal'];
    AOption: typeof import('@arco-design/web-vue')['Option'];
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm'];
    AResult: typeof import('@arco-design/web-vue')['Result'];
    ARow: typeof import('@arco-design/web-vue')['Row'];
    ASelect: typeof import('@arco-design/web-vue')['Select'];
    ASpace: typeof import('@arco-design/web-vue')['Space'];
    ASpin: typeof import('@arco-design/web-vue')['Spin'];
    AStep: typeof import('@arco-design/web-vue')['Step'];
    ASteps: typeof import('@arco-design/web-vue')['Steps'];
    ASwitch: typeof import('@arco-design/web-vue')['Switch'];
    ATable: typeof import('@arco-design/web-vue')['Table'];
    ATabPane: typeof import('@arco-design/web-vue')['TabPane'];
    ATabs: typeof import('@arco-design/web-vue')['Tabs'];
    ATextarea: typeof import('@arco-design/web-vue')['Textarea'];
    ATypographyParagraph: typeof import('@arco-design/web-vue')['TypographyParagraph'];
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
